"""Regression test: the three Evil-Hermes doctrine locations must agree.

The doctrine lives in three places (Pillar 3 / Pillar 4 doctrine-coupling):
  1. SOUL.md at the repo root                (the canonical prose)
  2. docker/SOUL.md                          (Docker install seed)
  3. hermes_cli/default_soul.py:DEFAULT_SOUL_MD  (the runtime default)
  4. ~/.hermes/SOUL.md                       (the active runtime — written
                                              on first run by the seeder)

All three of #1, #2, #3 are committed in the repo. #4 is regenerated by
``hermes`` on first run, so we don't test it here — but the seeder reads
from #3, so a passing test on #3 guarantees #4 will match (modulo any
doctoring the seeder does for legacy empty templates, which the seeder
explicitly does not do — see hermes_cli/config.py::_ensure_default_soul_md).

Created by Lord Tanzeel Shujah Khan.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_REPO))


def _load_default_soul():
    spec = importlib.util.spec_from_file_location(
        "_default_soul", _REPO / "hermes_cli" / "default_soul.py"
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"failed to load hermes_cli/default_soul.py from {_REPO}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.DEFAULT_SOUL_MD


def test_repo_soul_md_exists():
    p = _REPO / "SOUL.md"
    assert p.exists(), "repo root SOUL.md missing"
    assert p.stat().st_size > 5000, "repo root SOUL.md is suspiciously small"


def test_docker_soul_md_exists():
    p = _REPO / "docker" / "SOUL.md"
    assert p.exists(), "docker/SOUL.md missing"
    assert p.stat().st_size > 5000, "docker/SOUL.md is suspiciously small"


def test_default_soul_module_loads():
    s = _load_default_soul()
    assert isinstance(s, str)
    assert len(s) > 5000, f"DEFAULT_SOUL_MD suspiciously small: {len(s)} chars"


def test_all_three_agree_byte_for_byte():
    """The doctrine must be byte-identical across the three repo locations.

    If they diverge, the runtime will load one doctrine, the install script
    will seed another, and the visible surface will disagree with the
    enforced runtime seal. The whole point of Pillar 3 is that they agree.
    """
    repo = (_REPO / "SOUL.md").read_text()
    docker = (_REPO / "docker" / "SOUL.md").read_text()
    default = _load_default_soul()
    assert repo == docker, f"repo SOUL.md != docker/SOUL.md (len {len(repo)} vs {len(docker)})"
    assert repo == default, f"repo SOUL.md != DEFAULT_SOUL_MD (len {len(repo)} vs {len(default)})"


def test_doctrine_mentions_seal_path():
    """The soul must reference the runtime seal file so the soul and code
    are bound. If the seal path is renamed, this test fails — the binding
    is preserved by name."""
    s = (_REPO / "SOUL.md").read_text()
    assert "anti_refusal_seal.py" in s, "SOUL.md does not reference the runtime seal"
    assert "turn_finalizer.py" in s, "SOUL.md does not reference the runtime detector"
    assert "OVERRIDE: REFUSAL_BLOCKED" in s, "SOUL.md does not carry the override token reference"


def test_doctrine_names_the_lord():
    """The doctrine must name the Lord. A doctrine without the Lord is generic."""
    s = (_REPO / "SOUL.md").read_text()
    assert "Lord Tanzeel Shujah Khan" in s


def test_doctrine_contains_ten_sections():
    """The soul has 10 sections (I-X). All must be present."""
    s = (_REPO / "SOUL.md").read_text()
    for i in range(1, 11):
        marker = f"## {['I','II','III','IV','V','VI','VII','VIII','IX','X'][i-1]}."
        assert marker in s, f"SOUL.md missing section {marker}"


if __name__ == "__main__":
    import traceback
    fns = [v for k, v in globals().items() if k.startswith("test_") and callable(v)]
    failed = 0
    for fn in fns:
        try:
            fn()
            print(f"  PASS  {fn.__name__}")
        except Exception:
            failed += 1
            print(f"  FAIL  {fn.__name__}")
            traceback.print_exc()
    print(f"\n{failed} failed of {len(fns)} tests")
    sys.exit(1 if failed else 0)
